### ISSUE TITLE
How to setup startMonitoringSignificantLocationChanges

### ISSUE THREAD

**Issue by Rubioli** [michalchudziak/react-native-geolocation#198]
In my app, I'm using the library for iOS and for 2 purposes. One is to get the user's location for the use of the app and the second one is two keep the app "alive" so I can run a background job for syncing the data (using [react-native-background-actions)](https://github.com/Rapsssito/react-native-background-actions).

This is my `info.plist`:
```
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Your location is required to determine your region</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Your location is required to determine your region</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Your location is required to determine your region</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
		<string>processing</string>
	</array>
```

Code in my Cron job for background proccessing.
```
const getUserGeoLocation = () => {
  Geolocation.getCurrentPosition(
    success => {
      console.log(success);
    },
    error => {
      console.log("geoError", error);
    },
    {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000}
  );
}
```
My app got rejected in the App store with the description:

> Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not have any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to include features that require the persistent use of real-time location updates while the app is in the background.
> 
> 
> If your app does not require persistent real-time location updates, please remove the "location" setting from the UIBackgroundModes key. You may wish to use the significant-change location service or the region monitoring location service if persistent real-time location updates are not required for your app features.

So I'm wondering about two things. How can I use `startMonitoringSignificantLocationChanges` and if `startMonitoringSignificantLocationChanges` will keep my app alive in the background to sync data.

Any help is much appreciated

**Comment by michalchudziak** [comment]
You can specify `useSignificantLocation` in the options passed to the https://github.com/michalchudziak/react-native-geolocation#watchposition method. Judging from your description, I'm not sure whether it will solve your issue, as this library is not meant to be used to keep the app alive in the background, but to track the user's location. I'd recommend other solutions to keep the app alive.
