### ISSUE TITLE
The package '@react-native-community/geolocation' doesn't seem to be linked

### ISSUE THREAD

**Issue by yylingsj** [michalchudziak/react-native-geolocation#199]
## Environment
System
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 3.55 GB / 15.86 GB
Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
SDKs:
    Android SDK:
      API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 7, 8, 9
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    Visual Studio: 17.3.32901.215 (Visual Studio Enterprise 2022)
Languages:
    Java: 11.0.11
    Python: Not Found
npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
npmGlobalPackages:
    *react-native*: Not Found

## Platforms
Android

## Versions

- Android: 12
- react-native-geolocation: 3.0.1
- react-native: 0.63.3
- react: 16.13.1

## Description
just install with command
`yarn add @react-native-community/geolocation`
run the code below,i get error:
Error: The package '@react-native-community/geolocation' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo managed workflow

## Reproducible Demo
```
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION).then(granted => {
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        Geolocation.setRNConfiguration({
            skipPermissionRequests: true,
            locationProvider: 'android'
        })
        Geolocation.getCurrentPosition(
            ({ coords: { longitude, latitude } }) => {
                resolve({ success: true, longitude, latitude })
            },
            (error) => {
                resolve({ success: false })
                console.log(error.code, error.message);
            },
            { timeout: 3000, maximumAge: 0, enableHighAccuracy: true }
        )
    }
    else {
        resolve({ success: false })
    }
})
```

**Comment by yylingsj** [comment]
issue fixed, just downgrade the version "@react-native-community/geolocation": "1.4.2"

**Comment by ErikPinel** [comment]
is it a bug or am i doing something wrong?
