### ISSUE TITLE
iOS impossible to set location permission to always

### ISSUE THREAD

**Issue by ENT108** [michalchudziak/react-native-geolocation#239]
I followed the manual to every tiny bit, but all I get is use Allow When Use App permission.

What am I doing wrong? Any ideas?

Thanks!

**Comment by AlyssonBarbosa** [comment]
I have the same problem

**Comment by samuelgja** [comment]
https://github.com/zoontek/react-native-permissions/issues/521#issuecomment-777629554

But, on first load it do not ask for permission always when go to home screen (background) - only when app is killed and then to background.
