### ISSUE TITLE
Revision to work in Headless JS

### ISSUE THREAD

**Issue by valery-lavrik** [michalchudziak/react-native-geolocation#247]
The problem is that the definition of coordinates does not work in Headless mode because **currentActivity == null**
I propose to change the logic a little, and make sure that in this case the plugin still tries to determine the coordinates. 
I give an example on the screenshot

![image](https://user-images.githubusercontent.com/8047999/231367242-8c06657e-1396-409a-a8cc-e9b841dfa17f.png)

**Comment by michalchudziak** [comment]
Thanks! I see that there is some PR hanging. I need to review it and test it. I definitely want to get this feature merged.

**Comment by michalchudziak** [comment]
Shipped in version 3.1.0
