### ISSUE TITLE
How do I fix the '@react-native-community/geolocation' linking error on IOS using Expo bare workflow?

### ISSUE THREAD

**Issue by Taladkbp** [michalchudziak/react-native-geolocation#256]
I npm installed @react-native-community/geolocation to use on my app. I followed the documentation to give permission in the manifest file and the info.plist. It works perfectly fine on android but i get this linking error on IOS. The issue arises right when i import the library, not using yet. I am using expo bare workflow.

I have ran pod install, rebuilt my app just like suggested but the issue is still there only for IOS. I have tried 2 other libraries, expo location and react-native-background-location. They both have linking issues too.

## Error
ERROR  Error: The package '@react-native-community/geolocation' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow
, js engine: hermes
 LOG  Running "main" with {"rootTag":41,"initialProps":{}}
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace Talad.xcworkspace -configuration Debug -scheme Talad -destination id=1D6CC1FD-8C5F-41CF-8690-662A3F50FF1C

## Platforms
This issue is only on IOS, it works fine on Android

## Versions

- Android:
- iOS: 16.4 Phone14
- react-native-geolocation: "^3.0.6"
- react-native: "0.71.6"
- react:

**Comment by michalchudziak** [comment]
Make sure the module is linked properly, you can read more about auto linking [here](https://github.com/react-native-community/cli/blob/main/docs/autolinking.md). Closing
