### ISSUE TITLE
How to watch whether location permissions are obtained?

### ISSUE THREAD

**Issue by devethan** [michalchudziak/react-native-geolocation#257]
1. The app requests location permission
2. But user declines the permission 
3. After then, the permission is set in device settings
4. Check if permission is granted when returning to the foreground of app <- I am looking for a way to do this.

**Comment by michalchudziak** [comment]
I think the best way would be to use some permission management library :)

**Comment by devethan** [comment]
@michalchudziak Yes I think that would be great, thanks for the answer!
