### ISSUE TITLE
Merged fix not reflected in latest release

### ISSUE THREAD

**Issue by jkaufman** [michalchudziak/react-native-geolocation#311]
The fix referenced in https://github.com/michalchudziak/react-native-geolocation/pull/294 was merged into `develop` in January. However, the changes are [not present in the latest release](https://github.com/michalchudziak/react-native-geolocation/blob/master/android/src/main/java/com/reactnativecommunity/geolocation/PlayServicesLocationManager.java), `3.2.1`.

**Comment by jkaufman** [comment]
I believe the changes were lost due to a conflict with https://github.com/michalchudziak/react-native-geolocation/pull/280.

**Comment by jkaufman** [comment]
@michalchudziak The changes are still not present in this new release, `3.3.0`. Do you need me to issue a new PR?

**Comment by michalchudziak** [comment]
Thanks for highlighting that, let me take care of this. I'll ship the changes in the next release
